[workspace]
members = [
	"editor",
	"document-legacy",
	"proc-macros",
	"frontend/wasm",
	"frontend-svelte/wasm",
	"frontend/src-tauri",
	"node-graph/gcore",
	"node-graph/gstd",
	"node-graph/graph-craft",
	"node-graph/interpreted-executor",
	"node-graph/borrow_stack",
	"node-graph/node-macro",
	"node-graph/compilation-server",
	"node-graph/compilation-client",
	"node-graph/vulkan-executor",
	"node-graph/wgpu-executor",
	"node-graph/future-executor",
	"node-graph/gpu-compiler/gpu-compiler-bin-wrapper",
	"libraries/dyn-any",
	"libraries/bezier-rs",
	"website/other/bezier-rs-demos/wasm",
]

resolver = "2"

exclude = [
	"node-graph/gpu-compiler",
]

[workspace.dependencies]
specta = { git = "https://github.com/oscartbeaumont/specta.git", rev = "3d8f2d965077f1a02a58a814cb31cc9e66d558ea", features = ["glam", "functions", "tauri"] }

[profile.release.package.graphite-wasm]
opt-level = 3

[profile.dev.package.graphite-wasm]
opt-level = 3

[profile.release.package.graphite-wasm-svelte]
opt-level = 3

[profile.dev.package.graphite-wasm-svelte]
opt-level = 3

#[profile.dev]
#opt-level = 3

[patch.crates-io]
specta = { git = "https://github.com/oscartbeaumont/specta.git", rev = "3d8f2d965077f1a02a58a814cb31cc9e66d558ea" }
