[package]
name = "graphite-desktop"
version = "0.1.0"
description = "Graphite Desktop"
authors = ["Graphite Authors <contact@graphite.rs>"]
license = "Apache-2.0"
repository = ""
default-run = "graphite-desktop"
edition = "2021"
rust-version = "1.66.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "=1.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2", features = ["api-all", "devtools", "linux-protocol-headers", "wry"] }
axum = "0.6.1"
graphite-editor = { version = "0.0.0", path = "../../editor" }
document-legacy = { path = "../../document-legacy", package = "graphite-document-legacy" }
graph-craft = { path = "../../node-graph/graph-craft" }
graphene-core = { path = "../../node-graph/gcore", features = ["async", "std", "alloc"] }
chrono = "^0.4.23"
tokio = {version ="1", features = ["full"] }
ron = "0.8"
bezier-rs = { path = "../../libraries/bezier-rs" }

log = "0.4"
fern = {version = "0.6", features = ["colored"] }
futures = "0.3.25"
tauri-specta = { git = "https://github.com/oscartbeaumont/tauri-specta", rev = "2aa2a312324343fe1cfc8b2ba9db98ec236b7f09" }
specta = { workspace = true, features = ["functions"] }


[features]
gpu = ["graphite-editor/gpu"]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
